a = int(input("Enter 1st Number: "))
b = int(input("Enter 2nd Number: "))
c = int(input("Enter 3rd Number: "))
d = int(input("Enter 4th Number: "))
e = int(input("Enter 5th Number: "))
f = int(input("Enter 6th Number: "))
g = int(input("Enter 7th Number: "))
h = int(input("Enter 8th Number: "))
i = int(input("Enter 9th Number: "))
j = int(input("Enter 10th Number: "))
print(a + b + c + d + e + f + g + h + i + j)
